package ventanas;

import matrices.*;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author Bernal
 */
public class Calculator extends javax.swing.JDialog {
    
    // Se definen variables de los objetos matriz A, matriz B, y de la operacion de matrices
    private Matrices mtz1;
    private Matrices mtz2;
    private OpMatrices opMtz;
    private Menu lastWindows;
    
    // Modificar las variables declaradas anteriormente
    public void setMtz(Matrices mtz1, Matrices mtz2, OpMatrices mtz)
    {
        this.mtz1 = mtz1;
        this.mtz2 = mtz2;
        this.opMtz = mtz;
    }
    
    /**
     * Creates new form Matrices
     */
    public Calculator(java.awt.Frame parent, boolean modal) {
    	super(parent, modal);
        initComponents();
    }
    
    public void setLastWindows(Menu w)
    {
        lastWindows = w;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_matrizA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_matrizB = new javax.swing.JTextArea();
        btn_sumar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_restar = new javax.swing.JButton();
        btn_multiplicar = new javax.swing.JButton();
        lbl_titleMatrizA = new javax.swing.JLabel();
        lbl_titleMatrizB = new javax.swing.JLabel();
        lbl_desc = new javax.swing.JLabel();
        lbl_titleResultado = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_resultado = new javax.swing.JTextArea();
        lbl_infoTam = new javax.swing.JLabel();
        lbl_valor_axb = new javax.swing.JLabel();
        btn_exponente = new javax.swing.JButton();
        btn_escalar = new javax.swing.JButton();
        txt_escalarA = new javax.swing.JTextField();
        lbl_k1 = new javax.swing.JLabel();
        lbl_igual = new javax.swing.JLabel();
        txt_escalarB = new javax.swing.JTextField();
        lbl_k2 = new javax.swing.JLabel();
        btn_calcular = new javax.swing.JButton();
        txt_expoB = new javax.swing.JTextField();
        txt_expoA = new javax.swing.JTextField();
        lbl_operador = new javax.swing.JLabel();
        lbl_a = new javax.swing.JLabel();
        lbl_valor_a = new javax.swing.JLabel();
        lbl_b = new javax.swing.JLabel();
        lbl_valor_b = new javax.swing.JLabel();
        lbl_axb = new javax.swing.JLabel();
        tbn_mostrarOps = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        bnt_return = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora de Matrices");
        setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        setResizable(false);

        lbl_title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_title.setText("Calculadora de matrices");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(130, 86));

        txt_matrizA.setColumns(20);
        txt_matrizA.setRows(5);
        txt_matrizA.setMinimumSize(new java.awt.Dimension(2, 10));
        jScrollPane1.setViewportView(txt_matrizA);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(130, 96));

        txt_matrizB.setColumns(20);
        txt_matrizB.setRows(5);
        jScrollPane2.setViewportView(txt_matrizB);

        btn_sumar.setBackground(new java.awt.Color(204, 255, 255));
        btn_sumar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sumar.setText("Sumar");
        btn_sumar.setContentAreaFilled(false);
        btn_sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumarActionPerformed(evt);
            }
        });

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_restar.setText("Restar");
        btn_restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restarActionPerformed(evt);
            }
        });

        btn_multiplicar.setText("Multiplicar");
        btn_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicarActionPerformed(evt);
            }
        });

        lbl_titleMatrizA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titleMatrizA.setText("Matriz A:");

        lbl_titleMatrizB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titleMatrizB.setText("Matriz B:");

        lbl_desc.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        lbl_desc.setText("Separa los números con espacios y saltos de renglón (Enter)");

        lbl_titleResultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titleResultado.setText("Resultado:");

        jScrollPane3.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setToolTipText("");
        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setEnabled(false);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(130, 90));
        jScrollPane3.setRequestFocusEnabled(false);
        jScrollPane3.setWheelScrollingEnabled(false);

        txt_resultado.setBackground(new java.awt.Color(204, 204, 204));
        txt_resultado.setColumns(20);
        txt_resultado.setRows(5);
        txt_resultado.setAutoscrolls(false);
        txt_resultado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_resultado.setMinimumSize(new java.awt.Dimension(2, 10));
        jScrollPane3.setViewportView(txt_resultado);

        lbl_infoTam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_infoTam.setText("Tamaño de las matrices:");

        lbl_valor_axb.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbl_valor_axb.setText("0x0");

        btn_exponente.setText("Con exponente");
        btn_exponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exponenteActionPerformed(evt);
            }
        });

        btn_escalar.setText("Con escalar (k)");
        btn_escalar.setOpaque(false);
        btn_escalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_escalarActionPerformed(evt);
            }
        });

        txt_escalarA.setEditable(false);
        txt_escalarA.setBackground(new java.awt.Color(204, 204, 204));
        txt_escalarA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_escalarA.setForeground(new java.awt.Color(102, 102, 102));
        txt_escalarA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_escalarA.setText("1");
        txt_escalarA.setName(""); // NOI18N
        txt_escalarA.setOpaque(false);

        lbl_k1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_k1.setText("K:");
        lbl_k1.setEnabled(false);
        lbl_k1.setName("lbl_titleK1"); // NOI18N
        lbl_k1.setOpaque(true);

        lbl_igual.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_igual.setText("=");

        txt_escalarB.setEditable(false);
        txt_escalarB.setBackground(new java.awt.Color(204, 204, 204));
        txt_escalarB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_escalarB.setForeground(new java.awt.Color(102, 102, 102));
        txt_escalarB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_escalarB.setText("1");
        txt_escalarB.setName(""); // NOI18N
        txt_escalarB.setOpaque(false);

        lbl_k2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_k2.setText("K:");
        lbl_k2.setEnabled(false);
        lbl_k2.setName("lbl_titleK1"); // NOI18N
        lbl_k2.setOpaque(true);

        btn_calcular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        txt_expoB.setEditable(false);
        txt_expoB.setBackground(new java.awt.Color(204, 204, 204));
        txt_expoB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_expoB.setForeground(new java.awt.Color(102, 102, 102));
        txt_expoB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_expoB.setText("1");
        txt_expoB.setOpaque(false);

        txt_expoA.setEditable(false);
        txt_expoA.setBackground(new java.awt.Color(204, 204, 204));
        txt_expoA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_expoA.setForeground(new java.awt.Color(102, 102, 102));
        txt_expoA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_expoA.setText("1");
        txt_expoA.setOpaque(false);

        lbl_operador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_operador.setText("+");

        lbl_a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_a.setText("A:");

        lbl_valor_a.setText("0x0");

        lbl_b.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_b.setText("B:");

        lbl_valor_b.setText("0x0");

        lbl_axb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_axb.setText("AxB:");

        tbn_mostrarOps.setText("Mostrar operaciones");
        tbn_mostrarOps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_mostrarOpsActionPerformed(evt);
            }
        });

        bnt_return.setText("Regresar");
        bnt_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_returnActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar matriz como imagen");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Ajustes");
        jMenu1.add(jMenuItem1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Salir");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Copy");
        jMenu2.add(jMenuItem4);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Copiar resultado");
        jMenu2.add(jMenuItem7);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Pegar");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");

        jMenuItem5.setText("Credits");
        jMenu3.add(jMenuItem5);

        jMenuItem8.setText("Developer");
        jMenu3.add(jMenuItem8);

        jMenuItem11.setText("Version");
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(lbl_k1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_escalarA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_expoA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(lbl_k2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_operador)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_escalarB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_expoB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lbl_igual)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(lbl_titleMatrizA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_titleMatrizB)
                                        .addGap(64, 64, 64)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_titleResultado)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(lbl_title))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(lbl_desc)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separator, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_sumar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_restar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_multiplicar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbn_mostrarOps))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_escalar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_exponente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_calcular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_limpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_infoTam)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_valor_a)
                                .addGap(21, 21, 21)
                                .addComponent(lbl_b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_valor_b)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_axb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_valor_axb)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bnt_return)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_title)
                .addGap(18, 18, 18)
                .addComponent(lbl_desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt_expoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_operador)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_titleResultado)
                                    .addComponent(lbl_titleMatrizB))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(lbl_k2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_escalarB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_expoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbl_igual))
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_titleMatrizA)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(lbl_k1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_escalarA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_infoTam)
                    .addComponent(lbl_valor_axb)
                    .addComponent(lbl_a)
                    .addComponent(lbl_valor_a)
                    .addComponent(lbl_b)
                    .addComponent(lbl_valor_b)
                    .addComponent(lbl_axb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_exponente)
                    .addComponent(btn_escalar)
                    .addComponent(btn_limpiar)
                    .addComponent(btn_calcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sumar)
                    .addComponent(btn_restar)
                    .addComponent(btn_multiplicar)
                    .addComponent(tbn_mostrarOps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt_return)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Boton limpiar. Deja en blanco o en 1 según corresponda para regresar por defecto todo
    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        txt_matrizA.setText("");
        txt_matrizB.setText("");
        txt_resultado.setText("");
        txt_escalarA.setText("1");
        txt_escalarB.setText("1");
        txt_expoA.setText("1");
        txt_expoB.setText("1");
    }//GEN-LAST:event_btn_limpiarActionPerformed

    // Boton sumar.
    private void btn_sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumarActionPerformed
        // Hace que la letra del boton de resta y multiplicar se le quite lo negrita
        btn_restar.setFont(new java.awt.Font("Tahoma", 0, 11));
        btn_multiplicar.setFont(new java.awt.Font("Tahoma", 0, 11));
        // Hace que la letra del boton de suma se vuelva negrita
        btn_sumar.setFont(new java.awt.Font("Tahoma", 1, 11));
        // Cambia el texto del lbl_operador a '+' para saber que es suma
        lbl_operador.setText("+");
    }//GEN-LAST:event_btn_sumarActionPerformed

    // Boton escalar
    private void btn_escalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_escalarActionPerformed
        // Hace que caja de texto del escalar de A y B se pueda editar y se cambia el color de fondo a blanco
        txt_escalarA.setEditable(true);
        txt_escalarA.setBackground(Color.white);
        txt_escalarB.setEditable(true);
        txt_escalarB.setBackground(Color.white);
    }//GEN-LAST:event_btn_escalarActionPerformed

    // Boton exponente
    private void btn_exponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exponenteActionPerformed
        // Hace que caja de texto del exponente de A y B se pueda editar y se cambia el color de fondo a blanco
        txt_expoA.setEditable(true);
        txt_expoA.setBackground(Color.white);
        txt_expoB.setEditable(true);
        txt_expoB.setBackground(Color.white);
    }//GEN-LAST:event_btn_exponenteActionPerformed

    // Boton calcular
    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        // Extrae los datos que se utilizaran para realizar una operación
        String matrizA = txt_matrizA.getText(); // Matriz A
        String escalarA = txt_escalarA.getText(); // Escalar de matriz A
        String expoA = txt_expoA.getText(); // Exponente de matriz A
        String matrizB = txt_matrizB.getText(); // Matriz B
        String escalarB = txt_escalarB.getText(); // Escalar de matriz B
        String expoB = txt_expoB.getText(); // Exponente de matriz B
        char operacion = lbl_operador.getText().charAt(0); // Operación a utilizar (Extrae '+', '-' o '*')
        
       try
       {
    	   	// Inicializa nuevos objetos. Matriz A, B y operaciones de matrices
       		mtz1 = new Matrices(matrizA, escalarA, expoA);
       		mtz2 = new Matrices(matrizB, escalarB, expoB);
            opMtz = new OpMatrices(mtz1, mtz2, operacion);
            // Modifica las variables de matriz A, B y op de matrices. Para guardarlas en las variables de esta clase
            this.setMtz(mtz1, mtz2, opMtz);
                
            // Verifica que no haya errores para poder mostrar las matrices
            if(opMtz.calcular())
            	txt_resultado.setText(opMtz.mostrarMatrices());
                
            // Modifica los label donde se muestra el tamaño de las matrices (Deajo de la caja de texto de las matrices) y muestra su tamaño.
            lbl_valor_a.setText(mtz1.getTam());
            lbl_valor_b.setText(mtz2.getTam());
            lbl_valor_axb.setText(opMtz.getTam());
       } catch(Exception e) {
    	   System.out.println("TERMINADO."); // <---- MOSTRAR EN CONSOLA.
       }
    }//GEN-LAST:event_btn_calcularActionPerformed

    // Boton restar
    private void btn_restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restarActionPerformed
        btn_multiplicar.setFont(new java.awt.Font("Tahoma", 0, 11));
        btn_sumar.setFont(new java.awt.Font("Tahoma", 0, 11));
        btn_restar.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_operador.setText("-");
    }//GEN-LAST:event_btn_restarActionPerformed

    // Boton multiplicar
    private void btn_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicarActionPerformed
        btn_sumar.setFont(new java.awt.Font("Tahoma", 0, 11));
        btn_restar.setFont(new java.awt.Font("Tahoma", 0, 11));
        btn_multiplicar.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_operador.setText("*");
    }//GEN-LAST:event_btn_multiplicarActionPerformed

    // Boton Mostrar operaciones
    private void tbn_mostrarOpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_mostrarOpsActionPerformed
        // Crea el objeto de la ventana de las operaciones de matrices
        Operations frmOps1 = new Operations(this, true);
        
        // Si la matriz A y matriz B no esta vacias
        if(mtz1 != null && mtz2 != null)
        {
            // Cambiar el valor de la caja de texto agregando las operaciones realizadas, del objeto de matriz A, matriz B y de opMatrices
            frmOps1.setOps(mtz1.getMessage());
            frmOps1.setOps(mtz2.getMessage());
            frmOps1.setOps(opMtz.getMessage());
        }
        // Hace visible la ventana de operaciones de matrices
        frmOps1.setVisible(true);
    }//GEN-LAST:event_tbn_mostrarOpsActionPerformed

    private void bnt_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_returnActionPerformed
        this.dispose();
    }//GEN-LAST:event_bnt_returnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Calculator dialog = new Calculator(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_return;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_escalar;
    private javax.swing.JButton btn_exponente;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_multiplicar;
    private javax.swing.JButton btn_restar;
    private javax.swing.JButton btn_sumar;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_axb;
    private javax.swing.JLabel lbl_b;
    private javax.swing.JLabel lbl_desc;
    private javax.swing.JLabel lbl_igual;
    private javax.swing.JLabel lbl_infoTam;
    private javax.swing.JLabel lbl_k1;
    private javax.swing.JLabel lbl_k2;
    private javax.swing.JLabel lbl_operador;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_titleMatrizA;
    private javax.swing.JLabel lbl_titleMatrizB;
    private javax.swing.JLabel lbl_titleResultado;
    private javax.swing.JLabel lbl_valor_a;
    private javax.swing.JLabel lbl_valor_axb;
    private javax.swing.JLabel lbl_valor_b;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton tbn_mostrarOps;
    private javax.swing.JTextField txt_escalarA;
    private javax.swing.JTextField txt_escalarB;
    private javax.swing.JTextField txt_expoA;
    private javax.swing.JTextField txt_expoB;
    private javax.swing.JTextArea txt_matrizA;
    private javax.swing.JTextArea txt_matrizB;
    private javax.swing.JTextArea txt_resultado;
    // End of variables declaration//GEN-END:variables
}
