package ventanas;

import javax.swing.JOptionPane;

import matrices.Matrices;
import matrices.Operaciones;

/**
 *
 * @author Bernal
 */
public class InvCofactores extends javax.swing.JDialog {
    private Matrices mtz;
    private Operaciones ops;
    /**
     * Creates new form InvCofactores
     */
    public InvCofactores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        btn_ready = new javax.swing.JButton();
        btn_operations = new javax.swing.JButton();
        btn_saveMatriz = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_inversa = new javax.swing.JTextArea();
        lbl_inversa = new javax.swing.JLabel();
        lbl_matriz = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_matrizA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Inversa por Cofactores");

        btn_ready.setText("Sacar inversa");
        btn_ready.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_readyActionPerformed(evt);
            }
        });

        btn_operations.setText("Ver Operaciones");
        btn_operations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_operationsActionPerformed(evt);
            }
        });

        btn_saveMatriz.setText("Guardar matriz como imagen");

        btn_close.setText("Cerrar");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(130, 86));

        txt_inversa.setColumns(20);
        txt_inversa.setRows(5);
        txt_inversa.setMinimumSize(new java.awt.Dimension(2, 10));
        jScrollPane2.setViewportView(txt_inversa);

        lbl_inversa.setText("Matriz Inversa");

        lbl_matriz.setText("Matriz");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(130, 86));

        txt_matrizA.setColumns(20);
        txt_matrizA.setRows(5);
        txt_matrizA.setMinimumSize(new java.awt.Dimension(2, 10));
        jScrollPane1.setViewportView(txt_matrizA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_saveMatriz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_close)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_operations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ready))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lbl_matriz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_inversa)
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_inversa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_matriz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_operations)
                    .addComponent(btn_ready))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_saveMatriz)
                    .addComponent(btn_close)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
    	this.dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_readyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_readyActionPerformed
    	
    	String matrizA = txt_matrizA.getText();
    	
    	try
        {
    		mtz = new Matrices(matrizA, "1","1");
		    ops = new Operaciones(mtz);
		    txt_inversa.setText(ops.toStringInvCofactores());
        } catch(Exception e) {
     	   System.out.println("TERMINADO."); // <---- MOSTRAR EN CONSOLA.
        }
    }//GEN-LAST:event_btn_readyActionPerformed

    private void btn_operationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_operationsActionPerformed
    	
        // Verifica que la caja de texto de la matriz A y B no esten vacia.
        if(!mtz.equals(""))
        {
        	 // Crea el objeto de la ventana de las operaciones de matrices
            Operations frmOps1 = new Operations(this, true);
            
        	// Cambiar el valor de la caja de texto agregando las operaciones realizadas, del objeto de matriz A, matriz B y de opMatrices
	        frmOps1.setOps(mtz.getMessage());
	        frmOps1.setOps(ops.getMessage());
	        
	        frmOps1.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_operationsActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvCofactores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvCofactores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvCofactores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvCofactores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InvCofactores dialog = new InvCofactores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_operations;
    private javax.swing.JButton btn_ready;
    private javax.swing.JButton btn_saveMatriz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_inversa;
    private javax.swing.JLabel lbl_matriz;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JSeparator separator;
    private javax.swing.JTextArea txt_inversa;
    private javax.swing.JTextArea txt_matrizA;
    // End of variables declaration//GEN-END:variables
}
