package ventanas;

/**
 *
 * @author Bernal
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btn_calculator = new javax.swing.JButton();
        btn_traspuesta = new javax.swing.JButton();
        btn_invGJ = new javax.swing.JButton();
        btn_ecLinGJ = new javax.swing.JButton();
        btn_ecLinDet = new javax.swing.JButton();
        btn_determinante = new javax.swing.JButton();
        btn_invCofactores = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_help = new javax.swing.JButton();
        btn_about = new javax.swing.JButton();
        btn_compInvGJ = new javax.swing.JButton();
        lbl_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alegra Lineal");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        btn_calculator.setText("Suma, resta, multiplicación de matrices");
        btn_calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculatorActionPerformed(evt);
            }
        });

        btn_traspuesta.setText("Matriz traspuesta");
        btn_traspuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_traspuestaActionPerformed(evt);
            }
        });

        btn_invGJ.setText("Inversa: Gauss-Jordan");
        btn_invGJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_invGJActionPerformed(evt);
            }
        });

        btn_ecLinGJ.setText("Ecuaciones lineales: Gauss-Jordan");
        btn_ecLinGJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ecLinGJActionPerformed(evt);
            }
        });

        btn_ecLinDet.setText("Ecuaciones lineales: Determinantes");
        btn_ecLinDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ecLinDetActionPerformed(evt);
            }
        });

        btn_determinante.setText("Determinante de una matriz");
        btn_determinante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_determinanteActionPerformed(evt);
            }
        });

        btn_invCofactores.setText("Inversa: Cofactores");
        btn_invCofactores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_invCofactoresActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_help.setText("Help");

        btn_about.setText("About");
        btn_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutActionPerformed(evt);
            }
        });

        btn_compInvGJ.setText("Comprobación inversa GJ");
        btn_compInvGJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_compInvGJActionPerformed(evt);
            }
        });

        lbl_title.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        lbl_title.setText("Selecciona una opción:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_calculator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_invGJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ecLinGJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ecLinDet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_determinante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_invCofactores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_help)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_about)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_compInvGJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_traspuesta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_title)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_calculator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_traspuesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_determinante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ecLinGJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ecLinDet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_invGJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_compInvGJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_invCofactores)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salir)
                    .addComponent(btn_help)
                    .addComponent(btn_about))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {                                          
        System.exit(0);
    }                                         

    private void btn_calculatorActionPerformed(java.awt.event.ActionEvent evt) {                                               
        this.setVisible(false);
        Calculator opt = new Calculator();
        opt.setLastWindows(this);
        opt.setVisible(true);
    }                                              

    private void btn_traspuestaActionPerformed(java.awt.event.ActionEvent evt) {                                               
        new Traspuesta(this, true).setVisible(true);
    }                                              

    private void btn_determinanteActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        new Determinante(this, true).setVisible(true);
    }                                                

    private void btn_ecLinGJActionPerformed(java.awt.event.ActionEvent evt) {                                            
        new EcLinGJ(this, true).setVisible(true);
    }                                           

    private void btn_ecLinDetActionPerformed(java.awt.event.ActionEvent evt) {                                             
        new EcLinDet(this, true).setVisible(true);
    }                                            

    private void btn_invGJActionPerformed(java.awt.event.ActionEvent evt) {                                          
        new InvGJ(this, true).setVisible(true);
    }                                         

    private void btn_compInvGJActionPerformed(java.awt.event.ActionEvent evt) {                                              
        new CompInvGJ(this, true).setVisible(true);
    }                                             

    private void btn_invCofactoresActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        new InvCofactores(this, true).setVisible(true);
    }                                                 

    private void btn_aboutActionPerformed(java.awt.event.ActionEvent evt) {                                          
        new About(this, true).setVisible(true);
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_about;
    private javax.swing.JButton btn_calculator;
    private javax.swing.JButton btn_compInvGJ;
    private javax.swing.JButton btn_determinante;
    private javax.swing.JButton btn_ecLinDet;
    private javax.swing.JButton btn_ecLinGJ;
    private javax.swing.JButton btn_help;
    private javax.swing.JButton btn_invCofactores;
    private javax.swing.JButton btn_invGJ;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_traspuesta;
    private javax.swing.JLabel lbl_title;
    // End of variables declaration                   
}
